version: "3.7"
services:

  th:
    hostname: test_th
    container_name: test_th
    image: test_th
    # restart: always
    build:
      context: ./app
    ports:
      - 56789:56789
    environment:
      - DOMAIN=th.piper.finance
      - PORT=45678
      - REDIS_HOST=redis
      - REDIS_PORT=56789
      - REDIS_URL=redis://redis:6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_URL=mongodb://piperFinance:Piper2022@mongo:27017
      - API_LIST=./data/api_keys.json

    networks:
      - mongo_db
      - redis_db
      - default

networks:
  default:
    driver: bridge
    name: th_default
  redis_db:
    external:
      name: redis_db
  mongo_db:
    external:
      name: mongo_db
