version: "3.7"
services:

  app:
    hostname: app
    build:
      context: ./app
    ports:
      - 23456:23456
    env_file:
      - ./.env
    environment:
      - PORT=23456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=mongo
      - REDIS_PORT=27017
      - REDIS_URL=mongodb://mongo:6379

  worker:
    hostname: worker
    build:
      context: ./worker
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/4
      - CELERY_RESULT_URL=redis://redis:6379/5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - WAIT_BEFORE=15

networks:
  default:
    driver: bridge
    
