version: "3.7"
services:

  app:
    hostname: TH
    container_name: TH
    image: TH
    build:
      context: ./app
    ports:
      - 23456:23456
    environment:
      - DOMAIN=th.piper.finance
      - PORT=23456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=mongo
      - REDIS_PORT=27017
      - REDIS_URL=mongodb://mongo:27017
      - API_LIST=./data/api_keys.json

    networks:
      - mongo_db
      - redis_db

networks:
  redis_db:
    external:
      name: redis_db
  mongo_db:
    external:
      name: mongo_db


# networks:
#   default:
#     driver: bridge
    
