version: '3'

services:
  th:
    hostname: THV2 
    container_name: th_v2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6007:6007
    environment:
      API_URL: :6007
      PROJECT_NAME: TH
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_NAME: test_th
      SUPPORTED_CHAINS: 1,250,56,137,43114,42161,100,1284,10,1313161554 
      # NOTE: Supported by Unmarshal sdk
      # SUPPORTED_CHAINS: 1,250,56,137,43114,42161,42220,122,128,8217,10,25,100,1284,106,50,32769,1088,1101,5000,1313161554 
      LOG_LEVEL: debug
      REDIS_URL: redis://bs_redis:6379
      REDIS_DB: 5
      MONGO_URL: mongodb://piperFinance:Piper2022@mongo:27017
      MONGO_DBNAME: "TEST_TH"
      GITHUB_TOKEN: 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
      BS_URL: http://BS:6001
      PS_URL: http://PS:6002
      UA_URL: http://UA:6003
      TP_URL: http://TP:6004
      TH_URL: http://th:23456
      NT_URL: http://nt:34567
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "2"
    networks:
      - ps_net
      - bs_net
      - tp_net
      - ua_net
      - th_net
      - th_net_v2
      - nt_net
      - postgres_db
      - mongo_db
      - bs_redis_db

networks:
  postgres_db:
    external: true
    name: postgres_db
  mongo_db:
    external: true
    name: mongo_db
  th_net_v2:
    driver: bridge
    name: th_net_v2
  bs_redis_db:
    external: true
    name: bs_redis_db
  redis_db:
    external: true
    name: redis_db
  tp_net:
    external: true
    name: tp_net
  th_net:
    external: true
    name: th_default
  nt_net:
    external: true
    name: nt_default
  ps_net:
    external: true
    name: ps_net
  ua_net:
    external: true
    name: ua_net
  bs_net:
    external: true
    name: bs_net
